### PR TITLE
List tickets

### PR DESCRIPTION
**Pull request by zacharyehren**
Hey Ben, now that the client is up and running, I'm working on listing out the ticket subjects on the homepage. However, I'm having trouble figuring out how to pass data from the service to the controller. I've figured out how to specify the subject data from the tickets object, which you'll see in the ZenFactory service. I then have been playing around with passing this data over to the controller. Here are some things I've attempted:

* Creating an array and pushing each subject to the array
* In the Blocitoff app we did the following:

```javascript
$http(list_tasks).then(function successCallback(response) {
        TasksApiRequests.tasks = response.data;
      }
```
So I tried something similar here and doing:

```javascript
  ZenFactory.zendeskTicketSubjects = function() {
      zendesk.tickets.list().then(function(tickets){
        Zenfactory.tickets = tickets.data
    });
  }
```

Both of the methods listed above returned `undefined`. So I went back to the drawing board and refactored the `ZenFactory.zendeskTicketSubjects` function with similar logic to the BlocJams Angular project. Basically, returning the ticket object, then specify which data I want to show in the template. Right now, I'm just trying to show the ticket object on the homepage template but it's currently coming up blank. Let me know what you think.

### CODE REVIEW

**Comment by zacharyehren** [comment]
Update 9/17

I think I'm really close with being able to display tickets on the homepage. I believe I'm passing the data from the service to the controller correctly but still having trouble getting anything to display on the homepage template. One thing I noticed is that if I try to call `this.listSubjects = ZenFactory.tickets;` in the HomeCtrl, it logs as `undefined`. 

What makes it difficult to troubleshoot is that it's coming up blank instead of any errors or showing the literal brackets on the page. Screenshot below of what the homepage looks like. The tickets should be listed underneath "WUD UP".



screen shot 2017-09-17 at 3 17 50 pm

**Comment by bmneely** [comment]
Hmm, errors are definitely easier to debug than silent failure, which is the most frustrating thing in the world to debug. I'm taking a look and seeing if I can find out what is causing it. Silent failures can have a couple of causes, but typically they mean something you've added with your code has accidentally broken some fundamental part of the framework. The best way to debug (which isn't great, but I've had to do it many many times). Is to revert to a previous working state, and then apply your changes in as small as increments as possible. There's a couple of ways to do this (you can copy your files into other files. Use GitHub to push up your commits, and then revert locally. Or checkout a previous commit locally, and apply your changes. None of them are great, but they will get you there eventually. I'll let you know if I find anything via my debugging.

**Comment by zacharyehren** [comment]
Thanks Ben! To help narrow it down, I think I may just be calling the object incorrectly. When I the log following in the HomeCtrl - `console.log(this.listSubjects);` - it returns the entire ZenFactory object. Screenshot below. But if I try logging `console.log(this.listSubjects.tickets);`, it returns `undefined`. What's confusing is that I can see the tickets array in the object, as seen in the screenshot, but I'm not sure how to access it. I also think that's why the brackets on the homepage template are coming up blank because they are calling an `undefined` object. 

screen shot 2017-09-17 at 11 20 42 pm

**Comment by zacharyehren** [comment]
Interesting development! If I'm signed in and click "Sign Out", the data displays correctly on the homepage. Screenshot below.

screen shot 2017-09-18 at 6 24 52 pm

**Comment by zacharyehren** [comment]
Hello again! I just had my first weekly sync with my mentor at work and we went over the issue. It's not 100% resolved yet but I think we are almost there. I'll be working on this more tonight and will follow-up once I have an update.

**Comment by zacharyehren** [comment]
Alright, I'm completely stumped. In my meeting today, we updated the HomeCtrl to call the `ZenFactory.zendeskTicketSubjects` function then return a promise which saves `this.listSubjects` to `ZenFactory.tickets`. The code for this can be found below:

```javascript
  ZenFactory.zendeskTicketSubjects().then(function() { 
          this.listSubjects = ZenFactory.tickets;
          console.log(this.listSubjects);
        }.bind(this)
      );
```
I figured this should do the trick because we are invoking the function and then assigning the variable to the tickets array in the Zendesk object...but the issue is still happening. I'm wondering if there could be a hoisting issue happening. Check out the screenshot below. I have two logs for `this.listSubjects` in the HomeCtrl. One on line 6 which is inside the promise. Another is on line 9. The log on line 9 fires first, which returns `undefined` then the log on line 6 fires, which returns the array of tickets. 

screen shot 2017-09-19 at 7 03 35 pm

Additionally, I've noticed the same issue with line 12 of the HomeCtrl, which is assigning `this.user` to the `GoogleOauth` object. From what I'm gathering, it seems like the app is registering everything outside of the two Services first, rendering the template, then running the code in the Services. This may explain why the data appears on the template after I click `Sign Out`, because at that point, the script in the Services has already run. I hope that makes sense.

So all that said, I'm out of ideas. Let me know you're thoughts. 

Sidenote - I see that the HomeCtrl code is running twice, hence the double logs in the console. That's because I have the HomeCtrl manually registered on the index.html file to integrate the sign-in functionality. I'll fix this once this current issue is resolved.

**Comment by zacharyehren** [comment]
Just a quick note that I refactored the code so that the HomeCtrl wouldn't be called twice anymore.

**Comment by bmneely** [comment]
Hmm, nice refactoring and nice progress. I'm also stumped why it's still `undefined`. I'm going to call in the big guns and get my JS guru buddy to look at it tomorrow.

**Comment by bmneely** [comment]
Try:

```js
      ZenFactory.zendeskTicketSubjects().then(function() {
         $scope.$apply(function() {
            this.listSubjects = ZenFactory.tickets;
         });
        }.bind(this)
      );
```

From my buddy:
```
because if the data is definitely there
but angular isn’t recognizing it
it’s usually because the internal model isn’t registering that it needs to
pay attention to it
that’s a way of forcing that action
an external API call (like zendesk’s) isn’t going to be tracked by angular
only things like their `$http`, `$q`, and `$resource` services are
```

-- 
Ben Neely

On September 19, 2017 at 8:55:20 PM, zacharyehren (notifications@github.com)
wrote:

Just a quick note that I refactored the code so that the HomeCtrl wouldn't
be called twice anymore.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/zacharyehren/capstone/pull/5#issuecomment-330730979>,
or mute the thread

**Comment by zacharyehren** [comment]
That feedback makes total sense...but it still didn't do the trick :'(

Let's discuss more during our call tomorrow. I'm guessing this must be a common issue when dealing with external APIs.

**Comment by zacharyehren** [comment]
Hey Ben, just wanted to give you a heads up that I finished the display tickets feature on the homepage. It now displays all tickets. I'll eventually need to find out how to display only certain tickets because the final product will only display tickets that the CSM team sent in. But I'll hold off on that until I have the core functionality working. I did want to discuss a couple of things with you in the meantime. 

1. In order to get authorization to call the API, I have the username & token hardcoded into ZenFactory. I’m then encoding it before I send the API request, but how can I hide the hardcoded username & token within the app & github? Is it fine the way it is since I'm encoding it and just put the repo as private? Or is there a way to work around having the code in the file?

Here are the docs I referred to in order to figure out how to do the header authorization in the request:
https://stackoverflow.com/questions/34623050/using-http-get-to-retrieve-from-apizendesk-not-working
https://support.zendesk.com/hc/en-us/community/posts/204439007-401-using-AngularJS
https://support.zendesk.com/hc/en-us/articles/115000510267-Authentication-for-API-requests

2. I was receiving the following CORS error: 
`No 'Access-Control-Allow-Origin' header is present on the requested resource`

and used the following plugin to bypass it: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en-US

Is this best practice while in development? Or is there something I should add to the code to resolve the error?

**Comment by bmneely** [comment]
I'm confused, didn't we decide that this app will call your Rails backend API (which will make the actual call to ZenDesk). If so, then this won't use/store the ZenDesk username & token at all. Plus you shouldn't have the CORS issue either.

**Comment by zacharyehren** [comment]
I was thinking the same thing. I have the Rails API up and running but when I try and connect Angular's endpoint to Rails, it was requiring me to add the header in the request. Without the header, I get a 403 permission error. 

Maybe I'm doing this with the wrong approach? I basically mirrored the way I connected the endpoints in Blocitoff and using `$http` in Angular to make the request. But in Blocitoff, I also needed to hardcode the header which had username and password information.

**Comment by zacharyehren** [comment]
I was doing some more thinking about this and wondering if the issue is that my endpoint request in ZenFactory is going straight to the ZenDesk API instead of the Rails API. For example, check out the code below:

```javascript
ZenFactory.zendeskTicketSubjects = function() {
       var displayTickets = {
         method: 'GET',
         url: 'https://travelingyeti.zendesk.com/api/v2/tickets',
         headers: {
           'Authorization': 'Basic ' + window.btoa(client.username + '/token:' + client.token)
        }
       };
```

The URL is a route in the Rails API but could it be possible that it isn't being utilized in Rails and just going straight to Zendesk? I hope that makes sense. If I'm correct, is there a different way I should be communicating Angular to Rails?

**Comment by bmneely** [comment]
Yeah, I don't see anywhere where you're calling your Rails API in this code.

**Comment by zacharyehren** [comment]
Ohhhhhhh! It just came to me...instead of 'https://travelingyeti.zendesk.com/api/v2/tickets', it should be called to the local host the Rails API is living on. DUH. I'll start working on updating this after work today.

**Comment by bmneely** [comment]
Yep! :)

-- 
Ben Neely

On October 16, 2017 at 3:18:28 PM, zacharyehren (notifications@github.com)
wrote:

Ohhhhhhh! It just came to me...instead of '
https://travelingyeti.zendesk.com/api/v2/tickets', it should be called to
the local host the Rails API is living on. DUH. I'll start working on
updating this after work today.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/zacharyehren/capstone/pull/5#issuecomment-337046437>,
or mute the thread

**Pull request merged**
