### PR TITLE
begin createTicket function, create template + controller

### PR DESCRIPTION
**Pull request by zacharyehren**
Hey Ben, I'm now working on the front-end portion of creating tickets. I have everything squared away with the user form and the controller. What I'm stuck on is passing the info over to Rails. Here's my createTicket function in the Service: 

```javascript
ZenFactory.createTicket = function(subject, comment, submitter) {
        var createTicket = {
          method: 'POST',
          url: 'http://localhost:3000/api/tickets',
          data: {
            subject: subject,
            comment: comment,
            submitter: submitter
          }
        };
      }
```

And here's the method on Rails' end:

```ruby
def create(subject, comment_body, submitter)
    new_ticket = ZEN_CLIENT.tickets.create(:subject => subject, :comment => { :value => comment_body }, :via => { :source => { :from => { :name => submitter }}}, :requester => { :name => submitter })
  end
```
The issue is that when I try and submit the form, I'm getting the following error:

`"#<ArgumentError: wrong number of arguments (given 0, expected 3)>"`

So the subject, comment and submitter data aren't being passed through to Rails. I'm thinking that passing the data over successfully will require some updates in the code on both Angular and Rails but not sure how to go about doing this.

### CODE REVIEW

**Comment by bmneely** [comment]
Are you getting the error in your Rails or your Angular code?

**Comment by zacharyehren** [comment]
That error is coming from Rails side. Everything seems to be working properly on Angular.

**Comment by zacharyehren** [comment]
Hey Ben, just a heads up that this is fixed! My mentor at work and I figured it out. Everything was correct on the Angular side. I just had to update the `create` method in Rails by adding params.

**Comment by bmneely** [comment]
Perfect!

**Pull request closed without merging**
